FROM node:20-alpine

RUN apk add --no-cache git
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

RUN git clone https://github.com/unicodeveloper/globalthreatmap.git .

RUN pnpm install --frozen-lockfile || pnpm install

# All env vars - Railway passes these as build args
ARG NASA_FIRMS_API_KEY
ARG NEXT_PUBLIC_APP_MODE
ARG NEXT_PUBLIC_MAPBOX_TOKEN
ARG NEXT_PUBLIC_REDIRECT_URI
ARG NEXT_PUBLIC_VALYU_AUTH_URL
ARG NEXT_PUBLIC_VALYU_CLIENT_ID
ARG OPENAI_API_KEY
ARG OPENSKY_CLIENT_ID
ARG OPENSKY_CLIENT_SECRET
ARG VALYU_API_KEY
ARG VALYU_APP_URL
ARG VALYU_CLIENT_SECRET

# NEXT_PUBLIC_ vars must be available at build time for Next.js to inline them
ENV NEXT_PUBLIC_APP_MODE=$NEXT_PUBLIC_APP_MODE
ENV NEXT_PUBLIC_MAPBOX_TOKEN=$NEXT_PUBLIC_MAPBOX_TOKEN
ENV NEXT_PUBLIC_REDIRECT_URI=$NEXT_PUBLIC_REDIRECT_URI
ENV NEXT_PUBLIC_VALYU_AUTH_URL=$NEXT_PUBLIC_VALYU_AUTH_URL
ENV NEXT_PUBLIC_VALYU_CLIENT_ID=$NEXT_PUBLIC_VALYU_CLIENT_ID

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]
